/**
 * The permanent, built-in Welcome Screen covers (docs/ARCHITECTURE.md §26). These ship with the build: no database
 * row, no storage object, no network call. They are what the screen shows when nothing is published, and — this is
 * the part that matters — what each SLOT falls back to individually, so a promotion with mobile and tablet artwork
 * but no desktop one shows the desktop default rather than a phone image stretched across a monitor.
 *
 * Generated by scripts/render-hero.mjs from docs/assets/hero/night-beach-master.png: three crops of the one master,
 * each at several widths in AVIF and WebP. The blur placeholders below are the same crops at 24px; they paint
 * behind the photograph so there is never a blank background while it loads.
 *
 * Uploaded covers are a single WebP per variant, so only these defaults carry a multi-width srcset and an AVIF
 * alternative. That is the right way round: the defaults are on every cold visit, an upload is a campaign.
 */
import type { WelcomeCoverVariantKey } from "./variants";

export interface CoverImageSource {
  /** AVIF srcset when there is one (defaults only); null falls through to WebP. */
  avifSrcSet: string | null;
  webpSrcSet: string;
  /** The `<img>` src, i.e. the largest WebP. */
  src: string;
  /** Intrinsic size of `src`, so the element reserves its space and nothing shifts. */
  width: number;
  height: number;
  /** A data: URI painted underneath, so the area is never blank. */
  placeholder: string;
}

const HERO = "/hero";

function defaultSource(variant: string, widths: readonly [number, number][], placeholder: string): CoverImageSource {
  const last = widths[widths.length - 1]!;
  return {
    avifSrcSet: widths.map(([w]) => `${HERO}/default-${variant}-${w}.avif ${w}w`).join(", "),
    webpSrcSet: widths.map(([w]) => `${HERO}/default-${variant}-${w}.webp ${w}w`).join(", "),
    src: `${HERO}/default-${variant}-${last[0]}.webp`,
    width: last[0],
    height: last[1],
    placeholder,
  };
}

export const DEFAULT_COVER_SOURCES: Record<WelcomeCoverVariantKey, CoverImageSource> = {
  MOBILE: defaultSource("mobile", [[480, 853], [640, 1137], [828, 1471], [941, 1672]], "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACQBgCdASoYACsAPu1apk2ppKMiMBqtUTAdiUAXwHfJI/FDxQnfRed3atLJdFMtX2F7/Au+3GFMTmUybP8AAP76ZF+QQChNPQ40reRPEAqP5n1yXBM7QfAPyXKqLBtoq9hpI3w4iDPyYGha0elpym/mpkJ6RxRGV+NGIKIGGcu1YhpzThEAlVht7CQRcxJXg2crX1fLBYHvAn4z+JAAAA=="),
  TABLET: defaultSource("tablet", [[640, 854], [768, 1024], [941, 1255]], "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBQCdASoYACAAPu1iq1AppSOisBgIATAdiUAKvNL4PChrceTFRplV038+weDv5lvZcAD++96lqZCQ/sxSI1rYxN3m1Wim0JJB7/epU2IiyzCGyOcL5efEMnYCdJkBW0ncV9m3Ibhai+Wk1cZNSIfPh0vZG/jED6jZtp5V1BBUBa4aQAA="),
  DESKTOP: defaultSource("desktop", [[941, 529]], "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYgCdMoAC+pd14gRngqAD2AD+6UoluX0AttozcPm9WovWi6Xmjub2nXode9VDYqYdss+HPJqjajCh+QiSOUS47cBNroNmvYJ9rgmowAA="),
};
